export const modalState = {
    IS_OPEN: "CONTACT_MODAL_IS_OPEN",
    TOGGLE_SCROLL: "TOGGLE_SCROLL",
    MOBILE_MENU_IS_OPEN: "MOBILE_MENU_IS_OPEN",
    TOGGLE_TAGS_MODAL: "TOGGLE_TAGS_MODAL",
    TOGGLE_GDPR: "TOGGLE_GDPR",
    TOGGLE_HELLO: "TOGGLE_HELLO",
    SEARCH_IS_OPEN: "SEARCH_IS_OPEN",
    EMAILING_IS_OPEN: "EMAILING_IS_OPEN",
    TOGGLE_DISPLAY_EMAILING_HEADER: "TOGGLE_DISPLAY_EMAILING_HEADER",
}

export const sidebarActionTypes = {
    TYPE: "SIDEBAR",
    IS_OPEN: "SIDEBAR_IS_OPEN",
    SET_SIZES: "SIDEBAR_SET_SIZES",
    PING_SIZES: "PING_SIZES",
};

export const general = {
    MODAL_OPEN_CLASS: "no_overflow",
};

export const contactsActionTypes = {
    TYPE: "CONTACTS",
};

export const aboutActionTypes = {
    TYPE: "ABOUT",
};

export const vacanciesActionTypes = {
    TYPE: "VACANCIES",
};

export const articleActionTypes = {
    TYPE: "ARTICLE",
};

export const employeesActionTypes = {
    TYPE: "EMPLOYEES",
};

export const formsActionTypes = {
    SEND_REQUEST: "SEND_REQUEST",
    FILE_REQUEST: "FILE_REQUEST",
    SEND_SUCCESS: "SEND_SUCCESS",
    FILE_UPLOADED: "FILE_UPLOADED",
    SEND_FAIL: "SEND_FAIL",
    FILE_FAIL: "FILE_FAIL",
    RESET: "RESET",
    RECAPTCHA_FLAG: "RECAPTCHA_FLAG",
    RECAPTCHA_TOKEN: "RECAPTCHA_TOKEN",
    TOGGLE_STATE_ADBLOCK: "TOGGLE_STATE_ADBLOCK",
};

export const breakpointTypes = {
    SET_BREAKPOINT: "SET_BREAKPOINT",
};
export const headerTypes = {
    SET_HEADER_REF: "SET_HEADER_REF",
};
export const scrollBlockerTypes = {
    PUSH_SLIDER_OBJECT: "PUSH_SLIDER_OBJECT",
};

export const tagsActionTypes = {
    TYPE: "TAGS",

    SET_SELECTED: "SET_SELECTED",
    COPY_TAGS_BUFFER: "COPY_TAGS_BUFFER",
    SET_TAGS_BUFFER: "SET_TAGS_BUFFER",
    ADD_SELECTED_TAG: "ADD_SELECTED_TAG",
    REMOVE_SELECTED_TAG: "REMOVE_SELECTED_TAG",
    ADD_SELECTED_FILTER: "ADD_SELECTED_FILTER",
    REMOVE_SELECTED_FILTER: "REMOVE_SELECTED_FILTER",
    CLEAR_SELECTED_FILTERS: "CLEAR_SELECTED_FILTERS",
    PING_SELECTED_TAGS: "PING_SELECTED_TAGS",
    PING_SELECTED_FILTERS: "PING_SELECTED_FILTERS",
};

export const cardsTypes = {
    TYPE: "CARDS",
};

export const paginationTypes = {
    SET_PAGE: "SET_PAGE",
};

export const checkTypes = {
    TYPE: "CHEKS",
    SET_RETINA: "SET_RETINA",
    SET_WEBP: "SET_WEBP",
    SET_ONLINE: "SET_ONLINE",
};

export const searchTypes = {
    TYPE_INIT: "TYPE_INIT",
    TYPE_SEARCH: "TYPE_SEARCH",
    TYPE_DROPLIST: "TYPE_DROPLIST",
    SET_QUERY: "SET_QUERY",
};

export const careerTypes = {
    TYPE_CARDS: "CAREER_CARDS",
    TYPE_VACANCY: "CAREER_VACANCY",
    ADD_SELECTED_FILTER_FIRST: "ADD_SELECTED_FILTER_FIRST",
    REMOVE_SELECTED_FILTER_FIRST: "REMOVE_SELECTED_FILTER_FIRST",
    CLEAR_SELECTED_FILTERS_FIRST: "CLEAR_SELECTED_FILTERS_FIRST",
    ADD_SELECTED_FILTER_SECOND: "ADD_SELECTED_FILTER_SECOND",
    REMOVE_SELECTED_FILTER_SECOND: "REMOVE_SELECTED_FILTER_SECOND",
    CLEAR_SELECTED_FILTERS_SECOND: "CLEAR_SELECTED_FILTERS_SECOND",
    TOGGLE_AVAILABLE: "TOGGLE_AVAILABLE",
    SET_FILTERED_CARDS: "SET_FILTERED_CARDS",
};

export const routingTypes = {
    LAST_VISIT_TAG: "LAST_VISIT_TAG",
};

export const contactFormTypes = {
    SET_STEP: "SET_STEP",
    SET_FORM: "SET_FORM",
    SET_DATA: "SET_DATA",
    SET_SENDING: "SET_SENDING",
};

export const newAboutPage = {
    CHANGE_VISIBILITY_MOBILE_MENU: "CHANGE_VISIBILITY_MOBILE_MENU",
    SET_REF_RED_BLOCK: "SET_REF_RED_BLOCK",
    SET_PLAY_BLOCK: "SET_PLAY_BLOCK",
    SET_VIDEOS: "SET_VIDEOS",
    SET_VIDEOS_STATUS: "SET_VIDEOS_STATUS",
    SET_HERO_SLIDER_DELAYED: "SET_HERO_SLIDER_DELAYED",
    SET_BIG_BUSINESS_DELAYED: "SET_BIG_BUSINESS_DELAYED",
    SET_SLIDES_DELAYED: "SET_SLIDES_DELAYED",
    SET_EXPLOSION_DELAYED: "SET_EXPLOSION_DELAYED"
};
